Вариант решения по ТЗ 11 спринта.
kkn365/java-filmorate pull request #3
Opened 2024-11-25 17:30 UTC by kkn365

2024-11-26 10:50 UTC, YazykovMikhail requested changes

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Нет логирвоания контроллера, напомню:
Стандартный шаблон для логов
```

createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
```
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Поправь и для User

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/exception/CustomExceptionHandler.java
> +
500 — если возникло исключение.

```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
```

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends;
Стоит пометить
@JsonIgnore
ведь эти данные не должны участвовать в методах контроллера для работы с User, для работы с друзьми есть отдельные эгндпоинты, а тут они просто храняться

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> liked;
Стоит пометить
@JsonIgnore
ведь эти данные не должны участвовать в методах контроллера для работы с Film, для работы с лайками есть отдельные эгндпоинты, а тут они просто храняться

2024-11-26 10:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Рекомендую добавить поле и методы для него

```
private long rate = 0;

public void addLike(long userId) {
	userIds.add(userId);
	rate = userIds.size();
}

public void removeLike(long userId) {
	userIds.remove(userId);
	rate = userIds.size();
}
```
Что бы можно быо удобно подсчитывать рейтинг, когда добавляется или убирается лайк он будет увеличиваться/уменьшаться автоматически, а не каждый раз пробегаться по всем лайкам что бы подсчитать рейтинг

2024-11-28 19:09 UTC, kkn365 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
В ТЗ есть предложение использовать зависимость zalando

<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-spring-boot-starter</artifactId>
    <version>3.7.2</version>
</dependency>

, включение которой реализует логгирование в виде сообщений:

2024-11-28T22:03:41.688+03:00 TRACE 14491 --- [nio-8080-exec-2] org.zalando.logbook.Logbook              : {"origin":"local","type":"response","correlation":"d3109a74ff840901","duration":252,"protocol":"HTTP/1.1","status":200,"headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Date":["Thu, 28 Nov 2024 19:03:41 GMT"],"Keep-Alive":["timeout=60"],"Transfer-Encoding":["chunked"]},"body":{"id":1,"email":"Pascale.Kerluke@gmail.com","login":"GFj3zohm0o","name":"Miss Wilbert Klocko","birthday":"2005-03-02","friends":[]}}

Все тесты Postman записались в журнал и при этом не потребовалось использование аннотации @Slf4j, т.к. сообщения дублируются.

2024-11-29 11:56 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Единсвенное TRACE это конечно достаточно низкий уровень, будет много лишней информации, обычно эот уровень нужен для какого-то дебага. 
info - базовый уровень для логирвоания

2024-11-29 11:59 UTC, YazykovMikhail approved these changes

2024-11-29 11:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
Тоже стоит 
@JsonIgnore
ведь для реботы с рейтингом есть отдеьные эндпоинты

2025-01-03 08:13 UTC, merged